name: ecommerceELB
elbProtocol: HTTP
instanceProtocol: HTTP
instancePort: 80
elbPort: 80
targetGroupName:
  - 295JavaTargetGroupA
  - 295JavaTargetGroupB
securityGroupName:
  - 295JavaSecurityGroup
availablityZone:
  - us-west-2a
  - us-west-2b
  - us-west-2c